'use client';
import { useState } from 'react';
type Lang='zh'|'en';
const stories=[
{key:'ai',no:'01',tag:['正在折腾','MAKING'],title:['把 AI 当成新的游乐场','AI is my new playground'],body:['最近常用 Codex 做东西，刚做完一个 H5 小游戏。比起追热点，我更想知道它到底还能把边界推到哪里。','I recently built an H5 game with Codex. Less interested in hype, more interested in how far the boundary can move.'],note:['代码 / AI / 无限可能','CODE / AI / OPEN ENDS'],image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1800&q=88'},
{key:'iceland',no:'02',tag:['下一站','NEXT STOP'],title:['两个月后，去冰岛','Iceland, in two months'],body:['五年走遍五大洲。这个计划听起来很大，但真正需要做的，通常只是先买下一张机票。','Five continents in five years. Big plans usually begin with one booked flight.'],note:['冰川 / 风 / 远方','GLACIERS / WIND / ELSEWHERE'],image:'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=1800&q=88'},
{key:'dance',no:'03',tag:['身体练习','IN MOTION'],title:['Hiphop，还没跳帅','Hiphop, cool pending'],body:['帅是一辈子的事情。现在离帅还有一点距离，不过节拍已经找到了。','Cool is a lifelong pursuit. I am not quite there yet, but at least I found the beat.'],note:['节拍 / 汗 / 再来一次','BEAT / SWEAT / AGAIN'],image:'https://images.unsplash.com/photo-1556543366-995200222408?auto=format&fit=crop&w=1800&q=88'},
{key:'growth',no:'04',tag:['最近想明白','WORK IN PROGRESS'],title:['技术之外，也要升级','Upgrading beyond code'],body:['开始认真补职场沟通和 leadership 这两门课。英语也想学，只是执行进度比较有自己的想法。','Working on communication and leadership. English is also on the list, moving at a pace of its own.'],note:['沟通 / 判断 / 带好团队','CLARITY / JUDGMENT / LEADERSHIP'],image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=88'}];
const labels={zh:{nav:['精选','关于 Jasper','收藏夹'],search:'搜索好奇心',hello:'打个招呼',intro:'个人频道',about:'关于',line1:'大型互联网公司资深程序员。',line2:'喜欢研究没有标准答案的问题，也喜欢在工作之外重新学习怎么当个初学者。',badge:'INTJ-A · 天秤座',dream:'五年走遍五大洲。过两年，回家 GAP，陪猫猫狗狗。',cta:'留下暗号',mail:'不公开邮箱，回复看缘分',close:'收起',formTitle:'说点什么',name:'怎么称呼你',contact:'怎么联系你',message:'想聊什么',send:'先放进信箱',sent:'收到。正式上线后，这里会接到我的私人邮箱。',again:'再写一条'},en:{nav:['Featured','About Jasper','Bookmarks'],search:'Search curiosity',hello:'Say hello',intro:'PERSONAL CHANNEL',about:'About',line1:'Senior engineer at a major internet company.',line2:'I like problems without standard answers, and being a beginner again outside work.',badge:'INTJ-A · LIBRA',dream:'Five continents in five years. Then a gap year at home with cats and dogs.',cta:'Leave a signal',mail:'Private inbox, replies by chemistry',close:'Close',formTitle:'Say something',name:'Your name',contact:'How to reach you',message:'What is on your mind',send:'Drop it in',sent:'Got it. Once live, this goes to my private inbox.',again:'Write another'}};
export default function Home(){const[lang,setLang]=useState<Lang>('zh');const[active,setActive]=useState(0);const[open,setOpen]=useState(false);const[sent,setSent]=useState(false);const t=labels[lang],s=stories[active],li=lang==='zh'?0:1;const sendMail=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);const name=String(data.get('name')||'');const contact=String(data.get('contact')||'');const message=String(data.get('message')||'');const subject=encodeURIComponent(`${name} 从 Jasper 的个人网站发来消息`);const body=encodeURIComponent(`${message}\n\n称呼：${name}\n联系方式：${contact}`);window.location.href=`mailto:wangyao.jasper@gmail.com?subject=${subject}&body=${body}`;setSent(true)};return <main>
<header className="topbar"><a className="brand" href="#featured">JASPER<span>/</span></a><nav>{t.nav.map((item,i)=><a key={item} className={i===0?'active':''} href={i===1?'#about':'#featured'}>{item}</a>)}</nav><div className="tools"><span className="search">⌕&nbsp; {t.search}</span><button onClick={()=>setLang(lang==='zh'?'en':'zh')}>{lang==='zh'?'EN':'中'}</button><button className="helloButton" onClick={()=>setOpen(true)}>{t.hello}</button></div></header>
<div className="subnav"><div><span className="on">{t.intro}</span><span>TECH</span><span>TRAVEL</span><span>DANCE</span></div><span className="status"><i/> CURIOSITY ONLINE</span></div>
<section className="stage" id="featured" style={{'--hero-image':`url(${s.image})`} as React.CSSProperties}><div className="feature"><div className="featureCopy"><span className="tag">{s.tag[li]}</span><h1>{s.title[li]}</h1><p>{s.body[li]}</p><div className="meta"><span>{s.note[li]}</span><b>JASPER SELECTED</b></div></div></div><aside className="playlist" aria-label="Featured stories">{stories.map((story,i)=><button key={story.key} onClick={()=>setActive(i)} className={active===i?'selected':''}><span className="thumb" style={{backgroundImage:`url(${story.image})`}}/><span><small>{story.tag[li]}</small><strong>{story.title[li]}</strong></span><em>{story.no}</em></button>)}</aside></section>
<section className="about" id="about"><div className="aboutTitle"><span>{t.about}</span><h2>Jasper</h2><b>{t.badge}</b></div><div className="aboutCopy"><strong>{t.line1}</strong><p>{t.line2}</p></div><div className="dream"><span>FIVE-YEAR PLAN</span><p>{t.dream}</p></div><button className="signal" onClick={()=>setOpen(true)}><span>{t.cta}</span><small>{t.mail}</small><b>↗</b></button></section>
<footer><span>JASPER © 2026</span><span>CODE · MILES · RHYTHM</span><span>CURIOSITY STAYS ONLINE</span></footer>
{open&&<div className="drawerWrap" role="dialog" aria-modal="true" aria-label={t.formTitle}><button className="shade" aria-label={t.close} onClick={()=>setOpen(false)}/><section className="drawer"><button className="drawerClose" onClick={()=>setOpen(false)}>×</button><span className="tag">PRIVATE LINE</span><h2>{t.formTitle}</h2>{sent?<div className="sent"><b>✓</b><p>{t.sent}</p><button onClick={()=>setSent(false)}>{t.again}</button></div>:<form onSubmit={sendMail}><label>{t.name}<input name="name" required/></label><label>{t.contact}<input name="contact" required/></label><label>{t.message}<textarea name="message" rows={4} required/></label><button type="submit">{t.send}<span>↗</span></button></form>}</section></div>}</main>}
